#spring:
#  datasource:
#    name: test  #数据库名
#    url: jdbc:mysql://localhost:3306/test #url
#    username: root  #用户名
#    password: 123456  #密码
#    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo #错了
server:
  port: 8081
mail:
  smtp:
    host: smtp.qq.com
    username: 2724059421@qq.com
    password: joejlbqanbbzdfec
  from:
    name: yllcwt